import iconsGoogle from './google.png'
import iconsApple from './iphone.png'
import iconsFacebook from './facebook.png'
import IconHome from './home.png'
import IconHomeActive from './homeActive.png'
import IconFavorite from './favorite.png'
import IconFavoriteActive from './favoriteActive.png'
import IconExplore from './explore.png'
import IconExploreActive from './exploreActive.png'
import IconProfile from './user.png'
import IconProfileActive from './userActive.png'
import IconBars from './bars.png'
import IconBell from './bell.png'
import IconLocationWhite from './locationWhite.png'
import IconStart from './star.png'
import IconBack from './back.png'
import IconPen from './pen.png'
import IconSetting from './setting.png'
import IconLogout from './logout.png'
import IconNext from './next.png'

export {IconLocationWhite, IconBars, IconLogout, IconNext, IconSetting, IconPen, IconBack, IconStart, IconBell ,iconsApple, iconsGoogle, iconsFacebook, IconHome, IconHomeActive, IconFavorite, IconFavoriteActive, IconExplore, IconExploreActive, IconProfile, IconProfileActive}